language: php
php:
 -"7.4.3"
before install:
- php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update
after install:
- composer install
script: phpunit --configuration phpunit.xml --coverage-txt
